---
abstract: 'Eats all your (session) cookies in case Plack::Middleware::StrackTrace ate your HTTP headers.'
author:
  - 'Manni Heumann'
build_requires:
  ExtUtils::MakeMaker: 6.36
  HTTP::Request::Common: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-CookieMonster
no_index:
  directory:
    - inc
    - t
requires:
  Plack: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mannih/Plack-Middleware-CookieMonster.git
version: 0.02
